api:
  # image: webdevops/php-nginx:7.1
  image: payment/api:1.0.1
  ports:
    - "8080:80"
    - "8443:443"
  environment:
    - WEB_DOCUMENT_ROOT=/app/public

    - APP_ENV=production
    - APP_DEBUG=false
    - APP_KEY=base64:uLKsez60b/dXCqoF26uO/xa2FMHM+J52ftBW6zZgJc0=
    - APP_TIMEZONE=PRC

    - DB_CONNECTION=mysql
    - DB_HOST=192.168.1.211
    - DB_PORT=3306
    - DB_DATABASE=payment
    - DB_USERNAME=root
    - DB_PASSWORD=secretpw

    - CACHE_DRIVER=memcached
    - QUEUE_DRIVER=sync

    - LOG_SRV=192.168.1.213:9880
  volumes:
    - ./logs:/app/storage/logs
